### Create New Account
POST  http://lb-2643176f.elb.localhost.localstack.cloud:4004/auth/signup
Content-Type: application/json

{
  "email": "tenacioushamza@gmail.com",
  "username": "Hamza Ali",
  "password": "12345678",
  "role": "USER"
}