### Post Update Request
POST http://lb-06bcba2e.elb.localhost.localstack.cloud:4004/api/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZW5hY2lvdXNoYW16YUBnbWFpbC5jb20iLCJpYXQiOjE3NjQ1MzQwNDIsImV4cCI6MTc2NDUzNzY0Miwicm9sZSI6IlVTRVIifQ.PI5WH5IUn7aDVc_WjNK4qcgxagfKV_RLylXDfeke6so
Content-Type: application/json

{
  "name": "Abdul Wali Dal",
  "address": "Sindh, PK",
  "dateofBirth": "2005-09-06",
  "email": "hamzaali.array@gmail.com",
  "registeredDate": "2025-11-15"
}

###